export const agencyList = [
  {
    id: 1,
    name: 'Filip Travel',
    agencyPath: 'filip-travel',
    logo: '/images/agencies/FilipTravel.png',
    address: 'filip adresa',
    phone: '0123456',
    website: 'https://filiptravel.rs',
    websiteName: 'filiptravel.rs',
    licenceNum: '123',
    country: 'serbia',
    description:
      'Turistička agencija FILIP TRAVEL osnovana je 1993. godine u Beogradu - danas je jedan od vodećih turoperatora u Srbiji. Bavimo se organizacijom aranžmana u zemlji i inostranstvu, prodajom avio karata, kao i minibus prevozom putnika. Odličnu poziciju na tržištu obezbedili smo opredelivši se za kvalitet, sigurnost i otvoren odnos sa putnicima prema kojima smo godinama oblikovali svoju ponudu. Kao siguran partner kod svojih saradnika u inostranstvu - garantujemo adekvatan tretman za pravi odmor svojim klijentima',
  },
  {
    id: 2,
    name: 'Barcino',
    agencyPath: 'barcino',
    logo: '/images/agencies/BarcinoTours.png',
    address: 'barcino adresa',
    phone: '0123456',
    website: 'https://barcinotravel.rs',
    websiteName: 'barcinotravel.rs',
    licenceNum: '456',
    country: 'serbia',
    description:
      'Turistička agencija FILIP TRAVEL osnovana je 1993. godine u Beogradu - danas je jedan od vodećih turoperatora u Srbiji. Bavimo se organizacijom aranžmana u zemlji i inostranstvu, prodajom avio karata, kao i minibus prevozom putnika. Odličnu poziciju na tržištu obezbedili smo opredelivši se za kvalitet, sigurnost i otvoren odnos sa putnicima prema kojima smo godinama oblikovali svoju ponudu. Kao siguran partner kod svojih saradnika u inostranstvu - garantujemo adekvatan tretman za pravi odmor svojim klijentima',
  },
  {
    id: 3,
    name: 'BalkanFun',
    agencyPath: 'balkan-fun',
    logo: '/images/agencies/BalkanFun.png',
    address: 'BalkanFun adresa',
    phone: '0123456',
    website: 'https://balkanfuntravel.rs',
    websiteName: 'BalkanFuntravel.rs',
    licenceNum: '123',
    country: 'serbia',
    description:
      'Turistička agencija FILIP TRAVEL osnovana je 1993. godine u Beogradu - danas je jedan od vodećih turoperatora u Srbiji. Bavimo se organizacijom aranžmana u zemlji i inostranstvu, prodajom avio karata, kao i minibus prevozom putnika. Odličnu poziciju na tržištu obezbedili smo opredelivši se za kvalitet, sigurnost i otvoren odnos sa putnicima prema kojima smo godinama oblikovali svoju ponudu. Kao siguran partner kod svojih saradnika u inostranstvu - garantujemo adekvatan tretman za pravi odmor svojim klijentima',
  },
  {
    id: 4,
    name: 'Eurojet',
    agencyPath: 'eurojet',
    logo: '/images/agencies/Eurojet.png',
    address: 'Eurojet adresa',
    phone: '0123456',
    website: 'https://eurojettravel.rs',
    websiteName: 'Eurojettravel.rs',
    licenceNum: '123',
    country: 'bosnia',
    description:
      'Turistička agencija FILIP TRAVEL osnovana je 1993. godine u Beogradu - danas je jedan od vodećih turoperatora u Srbiji. Bavimo se organizacijom aranžmana u zemlji i inostranstvu, prodajom avio karata, kao i minibus prevozom putnika. Odličnu poziciju na tržištu obezbedili smo opredelivši se za kvalitet, sigurnost i otvoren odnos sa putnicima prema kojima smo godinama oblikovali svoju ponudu. Kao siguran partner kod svojih saradnika u inostranstvu - garantujemo adekvatan tretman za pravi odmor svojim klijentima',
  },
  {
    id: 5,
    name: 'Felix Travel',
    agencyPath: 'felix-travel',
    logo: '/images/agencies/FelixTravel.png',
    address: 'Felix adresa',
    phone: '0123456',
    website: 'https://felixtravel.rs',
    websiteName: 'Felixtravel.rs',
    licenceNum: '123',
    country: 'montenegro',
    description:
      'Turistička agencija FILIP TRAVEL osnovana je 1993. godine u Beogradu - danas je jedan od vodećih turoperatora u Srbiji. Bavimo se organizacijom aranžmana u zemlji i inostranstvu, prodajom avio karata, kao i minibus prevozom putnika. Odličnu poziciju na tržištu obezbedili smo opredelivši se za kvalitet, sigurnost i otvoren odnos sa putnicima prema kojima smo godinama oblikovali svoju ponudu. Kao siguran partner kod svojih saradnika u inostranstvu - garantujemo adekvatan tretman za pravi odmor svojim klijentima',
  },
  {
    id: 6,
    name: 'Fibula Travel',
    agencyPath: 'fibula-travel',
    logo: '/images/agencies/Fibula.png',
    address: 'Fibula adresa',
    phone: '0123456',
    website: 'https://fibulatravel.rs',
    websiteName: 'Fibulatravel.rs',
    licenceNum: '123',
    country: 'montenegro',
    description:
      'Turistička agencija FILIP TRAVEL osnovana je 1993. godine u Beogradu - danas je jedan od vodećih turoperatora u Srbiji. Bavimo se organizacijom aranžmana u zemlji i inostranstvu, prodajom avio karata, kao i minibus prevozom putnika. Odličnu poziciju na tržištu obezbedili smo opredelivši se za kvalitet, sigurnost i otvoren odnos sa putnicima prema kojima smo godinama oblikovali svoju ponudu. Kao siguran partner kod svojih saradnika u inostranstvu - garantujemo adekvatan tretman za pravi odmor svojim klijentima',
  },
  {
    id: 7,
    name: 'LUI Travel',
    agencyPath: 'lui-travel',
    logo: '/images/agencies/LUITravel.png',
    address: 'LUI adresa',
    phone: '0123456',
    website: 'https://LUItravel.rs',
    websiteName: 'LUItravel.rs',
    licenceNum: '123',
    country: 'macedonia',
    description:
      'Turistička agencija FILIP TRAVEL osnovana je 1993. godine u Beogradu - danas je jedan od vodećih turoperatora u Srbiji. Bavimo se organizacijom aranžmana u zemlji i inostranstvu, prodajom avio karata, kao i minibus prevozom putnika. Odličnu poziciju na tržištu obezbedili smo opredelivši se za kvalitet, sigurnost i otvoren odnos sa putnicima prema kojima smo godinama oblikovali svoju ponudu. Kao siguran partner kod svojih saradnika u inostranstvu - garantujemo adekvatan tretman za pravi odmor svojim klijentima',
  },
  {
    id: 8,
    name: 'NiTravel',
    agencyPath: 'ni-travel',
    logo: '/images/agencies/Nitravel.png',
    address: 'NiTravel adresa',
    phone: '0123456',
    website: 'https://nitravel.rs',
    websiteName: 'nitravel.rs',
    licenceNum: '123',
    country: 'macedonia',
    description:
      'Turistička agencija FILIP TRAVEL osnovana je 1993. godine u Beogradu - danas je jedan od vodećih turoperatora u Srbiji. Bavimo se organizacijom aranžmana u zemlji i inostranstvu, prodajom avio karata, kao i minibus prevozom putnika. Odličnu poziciju na tržištu obezbedili smo opredelivši se za kvalitet, sigurnost i otvoren odnos sa putnicima prema kojima smo godinama oblikovali svoju ponudu. Kao siguran partner kod svojih saradnika u inostranstvu - garantujemo adekvatan tretman za pravi odmor svojim klijentima',
  },
  {
    id: 9,
    name: 'Oktopod Travel',
    agencyPath: 'oktopod-travel',
    logo: '/images/agencies/Oktopod.png',
    address: 'Oktopod adresa',
    phone: '0123456',
    website: 'https://oktopodtravel.rs',
    websiteName: 'Oktopodtravel.rs',
    licenceNum: '123',
    country: 'bosnia',
    description:
      'Turistička agencija FILIP TRAVEL osnovana je 1993. godine u Beogradu - danas je jedan od vodećih turoperatora u Srbiji. Bavimo se organizacijom aranžmana u zemlji i inostranstvu, prodajom avio karata, kao i minibus prevozom putnika. Odličnu poziciju na tržištu obezbedili smo opredelivši se za kvalitet, sigurnost i otvoren odnos sa putnicima prema kojima smo godinama oblikovali svoju ponudu. Kao siguran partner kod svojih saradnika u inostranstvu - garantujemo adekvatan tretman za pravi odmor svojim klijentima',
  },
  {
    id: 10,
    name: 'Viva Travel',
    agencyPath: 'viva-travel',
    logo: '/images/agencies/VivaTravel.png',
    address: 'Viva adresa',
    phone: '0123456',
    website: 'https://vivatravel.rs',
    websiteName: 'Vivatravel.rs',
    licenceNum: '123',
    country: 'serbia',
    description:
      'Turistička agencija FILIP TRAVEL osnovana je 1993. godine u Beogradu - danas je jedan od vodećih turoperatora u Srbiji. Bavimo se organizacijom aranžmana u zemlji i inostranstvu, prodajom avio karata, kao i minibus prevozom putnika. Odličnu poziciju na tržištu obezbedili smo opredelivši se za kvalitet, sigurnost i otvoren odnos sa putnicima prema kojima smo godinama oblikovali svoju ponudu. Kao siguran partner kod svojih saradnika u inostranstvu - garantujemo adekvatan tretman za pravi odmor svojim klijentima',
  },
];
